title: Angularity
version: 0.0.1
 # baseurl: http://angularity.github.io/
canonifyurls: true
MetaDataFormat: yaml
footnotereturnlinkcontents: "↩"

theme: techdocshugotheme

 #permalinks:
 #  post: /:year/:month/:title/

params:
  Subtitle: An opinionated AngularJs build tool
  AuthorName: angularity
  GitHubUser: angularity
  GitHubRepo: node-angularity
  GitHubPagesBaseUrl: /
  GoogleAnalyticsId: UA-37884921-1
  GoogleAnalyticsDomain: bguiz.com
  RootRedirect:
    Url: /about/main
    Name: Introduction

indexes:
  category: categories
  tag: tags

menu:
  main:
    - Name: About
      Weight: 1000
      Identifier: about
    - Name: Getting Started
      Weight: 2000
      Identifier: start
    - Name: Guide
      Weight: 3000
      Identifier: guide

